// Copyright 2019-2023 Tauri Programme within The Commons Conservancy
// Copyright 2023-2023 CrabNebula Ltd.
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: MIT

use thiserror::Error;

/// All errors that can occur while running the updater.
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum Error {
    /// Endpoints are not sent.
    #[error("Updater does not have any endpoints set.")]
    EmptyEndpoints,
    /// IO errors.
    #[error(transparent)]
    Io(#[from] std::io::Error),
    /// Semver errors.
    #[error(transparent)]
    Semver(#[from] semver::Error),
    /// Serialization errors.
    #[error(transparent)]
    Serialization(#[from] serde_json::Error),
    /// Could not fetch a valid response from the server.
    #[error("Could not fetch a valid release JSON from the remote")]
    ReleaseNotFound,
    /// Unsupported app architecture.
    #[error("Unsupported application architecture, expected one of `x86`, `x86_64`, `arm` or `aarch64`.")]
    UnsupportedArch,
    /// Unsupported update fromat.
    #[error("Unsupported update format for the current target")]
    UnsupportedUpdateFormat,
    /// Operating system is not supported.
    #[error("Unsupported OS, expected one of `linux`, `macos` or `windows`.")]
    UnsupportedOs,
    /// Failed to determine updater package extract path
    #[error("Failed to determine updater package extract path.")]
    FailedToDetermineExtractPath,
    /// Url parsing errors.
    #[error(transparent)]
    UrlParse(#[from] url::ParseError),
    /// The platform was not found on the updater JSON response.
    #[error("the platform `{0}` was not found on the response `platforms` object")]
    TargetNotFound(String),
    /// Download failed
    #[error("`{0}`")]
    Network(String),
    /// `minisign_verify` errors.
    #[error(transparent)]
    Minisign(#[from] minisign_verify::Error),
    /// `base64` errors.
    #[error(transparent)]
    Base64(#[from] base64::DecodeError),
    /// UTF8 Errors in signature.
    #[error("The signature {0} could not be decoded, please check if it is a valid base64 string. The signature must be the contents of the `.sig` file generated by the Tauri bundler, as a string.")]
    SignatureUtf8(String),
    /// Temp dir is not on same mount mount. This prevents our updater to rename the AppImage to a temp file.
    #[error("temp directory is not on the same mount point as the AppImage")]
    TempDirNotOnSameMountPoint,
    /// The authenticated version embedded in the update signature does not match the advertised version.
    #[error("update metadata mismatch: the signed version `{signed}` does not match the advertised version `{advertised}`. The update may have been tampered with.")]
    SignedVersionMismatch {
        /// The version authenticated by the signature's trusted comment.
        signed: String,
        /// The version advertised in the (unsigned) update manifest.
        advertised: String,
    },
    /// The update signature does not contain the authenticated metadata required by the updater.
    #[error("the update signature does not contain the authenticated metadata (version/timestamp) required by the updater")]
    MissingSignedMetadata,
    /// The update signature is older than the configured maximum age.
    #[error("the update signature is stale: it was signed at unix timestamp {signed_timestamp}, which is older than the configured maximum age of {max_age_secs}s")]
    StaleSignature {
        /// The authenticated signing timestamp (seconds since the unix epoch).
        signed_timestamp: i64,
        /// The configured maximum signature age, in seconds.
        max_age_secs: u64,
    },
    /// The `reqwest` crate errors.
    #[error(transparent)]
    Reqwest(#[from] reqwest::Error),
    /// The `http` crate errors.
    #[error(transparent)]
    Http(#[from] http::Error),
    /// Error returned when persisting a temporary file fails.
    #[error(transparent)]
    PersistError(#[from] tempfile::PersistError),
}

/// Convenience alias for `cargo-packager-updater` crate Result type.
pub type Result<T> = std::result::Result<T, Error>;
