/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function cli(args: Array<string>, binName: string | undefined | null, callback: (...args: any[]) => any): void
export function logError(error: string): void
