/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function cli(args: Array<string>, binName?: string | undefined | null): void
export function package(config: string): void
export function logError(error: string): void
