/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Types of supported packages by [`@crabnebula/packager`](https://www.npmjs.com/package/@crabnebula/packager) */
export const enum PackageFormat {
  /** The macOS application bundle (.app). */
  App = "App",
  /** The macOS DMG package (.dmg). */
  Dmg = "Dmg",
  /** The Microsoft Software Installer (.msi) through WiX Toolset. */
  Wix = "Wix",
  /** The NSIS installer (.exe). */
  Nsis = "Nsis",
  /** The Linux Debian package (.deb). */
  Deb = "Deb",
  /** The Linux AppImage package (.AppImage). */
  AppImage = "AppImage",
}
/** Retrieve the resource path of your app, packaged with cargo packager. */
export function resourcesDir(packageFormat: PackageFormat): string;
